### ISSUE TITLE
Error when Using Execute Action  

### ISSUE THREAD

**Issue by Left-Hook-Digital** [davidyack/Xrm.Tools.CRMWebAPI#29]
Hello I am having an error when using the execute action method in the Node.js package. I am unable to determine if the error is due to the package or my setup. 

When using execute action with the QualifyLead action I receive the following error response

```
{ response: '{\r\n  "error":{\r\n    "code":"","message":"Request message has unresolved parameters.","innererror":{\r\n      "message":"Request message has unresolved parameters.","type":"Microsoft.Crm.CrmHttpException","stacktrace":"   at Microsoft.Crm.Extensibility.OData.CrmODataRoutingConvention.SelectAction(ODataPath odataPath, HttpControllerContext controllerContext, ILookup`2 actionMap)\\r\\n   at System.Web.OData.Routing.ODataActionSelector.SelectAction(HttpControllerContext controllerContext)\\r\\n   at System.Web.Http.ApiController.ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken)\\r\\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"\r\n    }\r\n  }\r\n}',
  headers: 
   { 'cache-control': 'no-cache',
     pragma: 'no-cache',
     'content-type': 'application/json; odata.metadata=minimal',
     expires: '-1',
     server: 'Microsoft-IIS/8.5',
     req_id: 'd209d3a2-2193-4398-aaca-9f1564efc916',
     'odata-version': '4.0',
     'x-aspnet-version': '4.0.30319',
     'x-powered-by': 'ASP.NET',
     date: 'Mon, 02 Jan 2017 21:10:56 GMT',
     connection: 'close',
     'content-length': '719',
     'set-cookie': [ 'crmf5cookie=!PW41x9uFy6IZ3b+9a0vrIWFrFaeDpFUcsH/WFpVQKiR8r7ngE7eQgT9vpXiS7XbW7Nq/92zrL/wtkiM=;secure; path=/' ],
     'strict-transport-security': 'max-age=31536000; includeSubDomains' } }
```

I have setup the parameters using the following page as a guide. 

https://msdn.microsoft.com/en-us/library/mt491164.aspx

below is the code I am running with sensitive data redacted.

```
var CRMWebAPI = require('CRMWebAPI');

var apiconfig = { APIUrl: 'https://myorghere.crm.dynamics.com/api/data/v8.0/', AccessToken: "access_token_here"};

var crmAPI = new CRMWebAPI(apiconfig);

console.log('hello')

var queryOptions = { 
    Top:10,
   // Select:['firstname', 'statecode'],
    Filter: "_createdby_value eq <userid>"
    //Filter: "statecode eq 0"
}


crmAPI.GetList('leads', queryOptions).then((response)=>{
               //console.log(response); 
               //using 4th index as I know it is an unqualified lead. This is for testing.
               var id = response.List[3].leadid;
               
               var params = {
                   "CreateAccount": false,
                   "CreateContact": true,
                   "CreateOpportunity":false,
                   "OpportunityCurrencyId":"currency_id_here",
                   "OpportunityCustomerId":null,
                   "SourceCampaignId":null,
                   "Status": 3,
                   "ProcessInstanceId":id
               };
               
               
               
               crmAPI.ExecuteAction('Microsoft.Dynamics.CRM.QualifyLead', params, 'leads' , id).then(function(res){
                   console.log(res);
               }).catch((error)=>{
                   console.log(error)
               })
             
                
            }).catch((error)=>{
                
                console.log(error)
            })
```

Any help you could provide I greatly appreciate. 

If the error is with my setup and not with the package I apologize for the issue in advance.

**Comment by davidyack** [comment]
Looks like there is a bug where it isn't adding the "/" before the action name for bound actions.  This will get fixed ASAP, however you can work around it using the following syntax for an action name

'/Microsoft.Dynamics.CRM.QualifyLead'

Thanks for bringing that to our attention

**Comment by davidyack** [comment]
This has been fixed in 1.3.3 of the nodejs lib.  if you are using npm, you can get the latest using 

npm update CRMWebAPI

Please confirm this resolves the issue
Thx

**Comment by Left-Hook-Digital** [comment]
Thank you for the prompt response.

I have update the npm package and tested the script again. 

I have received the same error message as above indicating unresolved parameters.

Do you think there is an additional issue or do you think it is setup?

**Comment by davidyack** [comment]
Yes I do. Take a look at the action page on the wiki for an example that works

________________________________

**Comment by Left-Hook-Digital** [comment]
I have setup the example from the wiki as you have it using the credentials for my account. 

There are no issues creating the lead. 

When the lead is qualified I receive the same error I had mentioned in my setup.

I have repeated the error below.

```
{ response: '{\r\n  "error":{\r\n    "code":"","message":"Request message has unresolved parameters.","innererror":{\r\n      "message":"Request message has unresolved parameters.","type":"Microsoft.Crm.CrmHttpException","stacktrace":"   at Microsoft.Crm.Extensibility.OData.CrmODataRoutingConvention.SelectAction(ODataPath odataPath, HttpControllerContext controllerContext, ILookup`2 actionMap)\\r\\n   at System.Web.OData.Routing.ODataActionSelector.SelectAction(HttpControllerContext controllerContext)\\r\\n   at System.Web.Http.ApiController.ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken)\\r\\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"\r\n    }\r\n  }\r\n}',
  headers: 
   { 'cache-control': 'no-cache',
     pragma: 'no-cache',
     'content-type': 'application/json; odata.metadata=minimal',
     expires: '-1',
     server: 'Microsoft-IIS/8.5',
     req_id: '1db9a756-66b6-4bc4-85c7-71c3d6a42cfc',
     'odata-version': '4.0',
     'x-aspnet-version': '4.0.30319',
     'x-powered-by': 'ASP.NET',
     date: 'Thu, 05 Jan 2017 15:02:13 GMT',
     connection: 'close',
     'content-length': '719',
     'set-cookie': [ 'crmf5cookie=!YmZHHGUrziCYWea9a0vrIWFrFaeDpBSemXxgoUXyDx3HQbMDftwmnQC9qLyygXPvEYbARfUWh++0cOQ=;secure; path=/' ],
     'strict-transport-security': 'max-age=31536000; includeSubDomains' } }
```

I can Create and GetList with this package with no issues but ExecuteAction seems to still have issues.

**Comment by davidyack** [comment]
Interesting, are you on 8.2 or an older release of CRM?

**Comment by Left-Hook-Digital** [comment]
From the about page it looks like we are on are on (8.0.1.360) (DB 8.0.1.359).

Is this version incompatible

**Comment by davidyack** [comment]
Not that I'm aware of, but there were a number of bugs with the CRM web API fixed since 8.0.1.  If I get a chance I will try resetting a sandbox to that version and testing - you might also try your code against a new trial organization as they will be 8.2.  You can also perform the same thing in Postman if you just want to post the json to that action to see if you get the same error

**Comment by Left-Hook-Digital** [comment]
Ill give that a try.

**Comment by davidyack** [comment]
Can you confirm you are using the fully qualified action name of 'Microsoft.Dynamics.CRM.QualifyLead' and not just 'QualifyLead'  That unresolved parameters will appear if you have an invalid name

**Comment by Left-Hook-Digital** [comment]
I am using Microsoft.Dynamics.CRM.QualifyLead as the action name.

**Comment by Left-Hook-Digital** [comment]
I have tested with a new trial account set to version 8.2

The action now works as expected with no errors.

It seems there is an issue with older crm version.

Knowing this fixes my issue as I can upgrade to 8.2

Thank you for your help.

**Comment by davidyack** [comment]
Thanks for the update.  I'm closing this issue for now, feel free to reach out if you hit any other issues
